from utils import read_settings

API_VERSION = "v1"
API_PREFIX = f"/api/{API_VERSION}"
PRINTER_NAME = "masung"
ACTIVE_BEERS_QTY = 2
DAYS_TO_EXPIRE = 5
CONTROL_BOARD_PORT = read_settings()['CONTROL_BOARD']['PORT']
SHOP_NAME = read_settings()['COMMON']['SHOP_NAME']
E_INTAKE_AIR_AFTER_POUR_AMOUNT = int(read_settings()['CONTROL_BOARD']['INTAKE_AIR_AFTER_POUR_AMOUNT'])
E_INTAKE_AIR_AFTER_POUR_BLINK_TIMEOUT = int(read_settings()['CONTROL_BOARD']['INTAKE_AIR_AFTER_POUR_BLINK_TIMEOUT'])
E_BEER_POUR_FAIL_TIMEOUT = int(read_settings()['CONTROL_BOARD']['BEER_POUR_FAIL_TIMEOUT'])
E_ITERATION_TIMEOUT_BEFORE = float(read_settings()['CONTROL_BOARD']['ITERATION_TIMEOUT_BEFORE'])
E_ITERATION_TIMEOUT_AFTER = float(read_settings()['CONTROL_BOARD']['ITERATION_TIMEOUT_AFTER'])
E_BEER_POUR_SPLIT_PERCENT = int(read_settings()['CONTROL_BOARD']['BEER_POUR_SPLIT_PERCENT'])
E_BLINK_INTAKE_AIR_TIMEOUT_BEFORE = int(read_settings()['CONTROL_BOARD']['BLINK_INTAKE_AIR_TIMEOUT_BEFORE'])
E_BLINK_INTAKE_AIR_TIMEOUT_AFTER = int(read_settings()['CONTROL_BOARD']['BLINK_INTAKE_AIR_TIMEOUT_AFTER'])
E_TIMEOUT_BETWEEN_INTAKE_AIR_ITERATION = float(read_settings()['CONTROL_BOARD']['TIMEOUT_BETWEEN_INTAKE_AIR_ITERATION'])
