from utils import read_settings

# api
API_VERSION = "v1"
API_PREFIX = f"/api/{API_VERSION}"
# general
SHOP_NAME = read_settings()['COMMON']['SHOP_NAME']
PRINTER_NAME = "masung"
ACTIVE_BEERS_QTY = 2
DAYS_TO_EXPIRE = 5
# cron
CRON_HOUR = '13'
CRON_MINUTE = '57'
# board
CONTROL_BOARD_PORT = read_settings()['CONTROL_BOARD']['PORT']
E_INTAKE_AIR_AFTER_POUR_AMOUNT = int(read_settings()['CONTROL_BOARD']['INTAKE_AIR_AFTER_POUR_AMOUNT'])
E_INTAKE_AIR_AFTER_POUR_BLINK_TIMEOUT = int(read_settings()['CONTROL_BOARD']['INTAKE_AIR_AFTER_POUR_BLINK_TIMEOUT'])
E_BEER_POUR_FAIL_TIMEOUT = int(read_settings()['CONTROL_BOARD']['BEER_POUR_FAIL_TIMEOUT'])
E_ITERATION_TIMEOUT_BEFORE = float(read_settings()['CONTROL_BOARD']['ITERATION_TIMEOUT_BEFORE'])
E_ITERATION_TIMEOUT_AFTER = float(read_settings()['CONTROL_BOARD']['ITERATION_TIMEOUT_AFTER'])
E_BEER_POUR_SPLIT_PERCENT = int(read_settings()['CONTROL_BOARD']['BEER_POUR_SPLIT_PERCENT'])
E_BLINK_INTAKE_AIR_TIMEOUT_BEFORE = int(read_settings()['CONTROL_BOARD']['BLINK_INTAKE_AIR_TIMEOUT_BEFORE'])
E_BLINK_INTAKE_AIR_TIMEOUT_AFTER = int(read_settings()['CONTROL_BOARD']['BLINK_INTAKE_AIR_TIMEOUT_AFTER'])
E_TIMEOUT_BETWEEN_INTAKE_AIR_ITERATION = float(read_settings()['CONTROL_BOARD']['TIMEOUT_BETWEEN_INTAKE_AIR_ITERATION'])
# telegram
TELEGRAM_TOKEN = "5470129212:AAF4uPVHv207KwTJV5-zdt8MxFyG53ceB88"
TELEGRAM_CHAT_ID = "-1001861798952"
TELEGRAM_BASE_URL = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}"
